train_file: 'data/train.jsonline'
val_file: 'data/val.jsonline'                
test_file: 'data/test.jsonline'

image_root: '/mnt/c/Users/aleja/Desktop/Msc Project/images/'

image_res: 256
batch_size_train: 32 
batch_size_test: 64 

alpha: 0.4
distill: False
warm_up: False

bert_config: '/vol/teaching/HernandezDiazProject/understandingVLmodels/Models/ALBEF/github/configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







